site_name: SdamGIA API
site_description: Unofficial API for SdamGIA educational portal for exam preparation.
site_author: dinaprk
site_url: https://dinaprk.github.io/sdamgia-python

repo_name: dinaprk/sdamgia-python
repo_url: https://github.com/dinaprk/sdamgia-python
edit_uri: edit/master/docs/

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb-outline
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/lightbulb
        name: "Switch to light mode"

nav:
  - Index: "index.md"
  - API: "api.md"
  - Types: "types.md"
  - Enums: "enums.md"
  - Utils: "utils.md"

extra_css:
  - "extra/tweaks.css"

markdown_extensions:
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - sdamgia

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_(?!defer_build_mode)"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          paths: [sdamgia]
          import:
            - https://docs.python.org/3/objects.inv
