site_name: SdamGIA API
site_author: dinaprk
site_description: Unofficial API for SdamGIA educational portal for exam preparation.

repo_name: dinaprk/sdamgia-python
repo_url: https://github.com/dinaprk/sdamgia-python
edit_uri: edit/master/docs/

nav:
  - Index: "index.md"
  - Reference:
      - API: "reference/api.md"
      - Types: "reference/types.md"

watch:
  - docs
  - sdamgia

theme:
  name: material
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.tracking
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: "Switch to dark mode"
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: "Switch to light mode"

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: source
            separate_signature: true
            filters: ["!^_(?!defer_build_mode)"]
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            show_signature_annotations: true
            signature_crossrefs: true
          paths: [sdamgia]
          import:
            - https://docs.python.org/3/objects.inv

markdown_extensions:
  - toc:
      permalink: true
      title: Page contents
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.extra
  - pymdownx.superfences
